
[mypy]
python_version = 3.10
plugins = mypy_django_plugin.main

disallow_untyped_defs = True
check_untyped_defs = True
warn_unused_ignores = True
warn_return_any = True
strict_optional = True

exclude = migrations

follow_imports = normal

[mypy.plugins.django-stubs]
django_settings_module = app.settings
